# This is a basic workflow to help you get started with Actions

name: Bundle & Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.16.1
      - run: npm ci
      - run: npm run bundle
      - run: npm --prefix=packages/zahlenspiel-backend test
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.0.9
        env:
          ARGS: "-rtgoDzvO --no-links"
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          SOURCE: "bundle/"
          TARGET: ${{ secrets.DEPLOY_TARGET }}
